- name: Deploy Go Server
  hosts: go-server
  gather_facts: true
  become: true
  roles:
    - sys_package
    - install_go_server
    - git


- name: Deploy Go Agent
  hosts: go-agent
  gather_facts: true
  become: true
  roles:
    - sys_package
    - user_go_agent
    - install_go_agent
    - git
    - maven
